[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "rsrcdump"
version = "0.1.0"
repository = "https://github.com/jorio/rsrcdump"
description = "Extract and convert Mac resource forks"
authors = ["Iliyas Jorio <github@jor.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
rsrcdump = "rsrcdump.__main__:main"

[tool.mypy]
files = ["rsrcdump/",]
show_column_numbers = true
show_error_codes = true
show_traceback = true
disallow_any_decorated = true
disallow_any_unimported = true
ignore_missing_imports = true
local_partial_types = true
no_implicit_optional = true
strict = true
warn_unreachable = true
